# Generated by Django 4.0.3 on 2022-03-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
